version: '3.3'
services:
  pet_clinic_db:
    container_name: pet_clinic_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
    # <Port exposed> : < MySQL Port running inside container>
    - '3306:3306'
    expose:
    # Opens port 3306 on the container
    - '3306'
  pet_clinic_app:
    container_name: pet_clinic_app
    restart: always
    build: .
    image: pet_clinic_app
    working_dir: /app
    volumes:
    - ./target:/app/target
    - ./wait-for-it.sh:/app/wait-for-it.sh
    ports:
    - "5005:5005"
    - "8080:8080"
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh pet_clinic_db:3306 && /usr/local/openjdk-11/bin/java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005 -jar /app/target/petclinic-0.0.1-SNAPSHOT.jar"
    depends_on:
    - pet_clinic_db