spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://pet_clinic_db:3306/petclinic?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: idclip666hell@gmail.com
    password: doomforever
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 3000
  jackson:
    serialization:
      write_dates_as_timestamps: false

# token - 5hs
access-token-validity-seconds: 18000
signing-key: "cGV0Y2xpbmljX1RUUFMyMDE5"
issuer: "https://petclinic.com"

header-string: Authorization

admin:
  name: "Admin"
  email: "petclinicadmin@gmail.com"
  password: "petClinicAdminPassword"

upload-files-folder: "./images/"
